apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python_app
  namespace: argocd
spec:

  source:
    repoURL: https://github.com/Benn1440/AgroCD_Application.git
    targetRevision: main
    path: K8s 
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: myappns

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true